### ISSUE TITLE
Compilation error with kernel 4.3: error: too many arguments to function ‘bio_endio’

### ISSUE THREAD

**Issue by marcin-github** [akiradeveloper/dm-writeboost#90] opened 2015-11-03 09:45 UTC
Hi!
On kernel-4.3 dm-writeboost fails to compile:
>[...]
  CC [M]  /var/tmp/portage/sys-fs/dm-writeboost-2.1.0/work/dm-writeboost-2.1.0/src/dm-writeboost-daemon.o
/var/tmp/portage/sys-fs/dm-writeboost-2.1.0/work/dm-writeboost-2.1.0/src/dm-writeboost-daemon.c: In function ‘process_deferred_barriers’:
/var/tmp/portage/sys-fs/dm-writeboost-2.1.0/work/dm-writeboost-2.1.0/src/dm-writeboost-daemon.c:69:5: error: too many arguments to function ‘bio_endio’
     bio_endio(bio, 0);
     ^
In file included from include/linux/device-mapper.h:11:0,
                 from /var/tmp/portage/sys-fs/dm-writeboost-2.1.0/work/dm-writeboost-2.1.0/src/dm-writeboost.h:36,
                 from /var/tmp/portage/sys-fs/dm-writeboost-2.1.0/work/dm-writeboost-2.1.0/src/dm-writeboost-daemon.c:20:
include/linux/bio.h:433:13: note: declared here
 extern void bio_endio(struct bio *);
             ^
/var/tmp/portage/sys-fs/dm-writeboost-2.1.0/work/dm-writeboost-2.1.0/src/dm-writeboost-daemon.c:71:5: error: too many arguments to function ‘bio_endio’
     bio_endio(bio, -EIO);
     ^
In file included from include/linux/device-mapper.h:11:0,
                 from /var/tmp/portage/sys-fs/dm-writeboost-2.1.0/work/dm-writeboost-2.1.0/src/dm-writeboost.h:36,
                 from /var/tmp/portage/sys-fs/dm-writeboost-2.1.0/work/dm-writeboost-2.1.0/src/dm-writeboost-daemon.c:20:
include/linux/bio.h:433:13: note: declared here
 extern void bio_endio(struct bio *);
[...]

**Comment by akiradeveloper** [comment] 2015-11-03 11:53
Thanks.

It should get fixed with a change `bio_endio(bio, e)` -> `bio->bi_error =e; bio_endio(bio)` 

ie. https://fossies.org/diffs/linux/4.2_vs_4.3-rc1/block/blk-core.c-diff.html

You can send me a pull request if you want to.

**Comment by akiradeveloper** [comment] 2015-11-27 06:36
Still needs fixing. I will do this when I have a time. Sorry

(I am fucking busy with my work)

**Comment by onlyjob** [comment] 2016-01-04 10:38
Any progress please? Linux-4.3 entered Debian "testing" and "unstable" so this bug became a real problem...

**Comment by akiradeveloper** [comment] 2016-01-04 11:14
No. Do you need this fix immediately?
If so, I will make my time this weekend (but I need to fix my test machine that's broken)

**Comment by akiradeveloper** [comment] 2016-01-04 12:15
I just started to hack...

maybe, something like this.
I will test with 4.3 only because this fix is trivial

```c
akira@Hercules:~/dm-writeboost/src$ git di
diff --git a/src/dm-writeboost-daemon.c b/src/dm-writeboost-daemon.c
index a1493b5..d4e90d2 100644
--- a/src/dm-writeboost-daemon.c
+++ b/src/dm-writeboost-daemon.c
@@ -66,9 +66,9 @@ static void process_deferred_barriers(struct wb_device *wb, struct flush_job *jo
                struct bio *bio;
                while ((bio = bio_list_pop(&job->barrier_ios))) {
                        if (is_live(wb))
-                               bio_endio(bio, 0);
+                               bio_endio_compat(bio, 0);
                        else
-                               bio_endio(bio, -EIO);
+                               bio_endio_compat(bio, -EIO);
                }
        }
 }
diff --git a/src/dm-writeboost-target.c b/src/dm-writeboost-target.c
index 2f645b0..8dc8d67 100644
--- a/src/dm-writeboost-target.c
+++ b/src/dm-writeboost-target.c
@@ -796,9 +796,9 @@ static int do_process_write(struct wb_device *wb, struct metablock *write_pos, s
        }

        if (is_live(wb))
-               bio_endio(bio, 0);
+               bio_endio_compat(bio, 0);
        else
-               bio_endio(bio, -EIO);
+               bio_endio_compat(bio, -EIO);

        return DM_MAPIO_SUBMITTED;
 }
diff --git a/src/dm-writeboost.h b/src/dm-writeboost.h
index 5741c0e..1a8577a 100644
--- a/src/dm-writeboost.h
+++ b/src/dm-writeboost.h
@@ -43,6 +43,18 @@

 /*----------------------------------------------------------------------------*/

+static void bio_endio_compat(struct bio *bio, int error)
+{
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,3,0)
+       bio->bi_error = error;
+       bio_endio(bio);
+#else
+       bio_endio(bio, error);
+#endif
+}
+
+/*----------------------------------------------------------------------------*/
+
 /*
  * The detail of the disk format (SSD)
  * -----------------------------------
```

**Comment by akiradeveloper** [comment] 2016-01-04 12:16
oh... 4.4-rc8...

**Comment by akiradeveloper** [comment] 2016-01-04 12:26
ruby compiled (seem to be good

**Comment by akiradeveloper** [comment] 2016-01-04 12:26
but device-mapper-test-suite goes on (for hours..

**Comment by akiradeveloper** [comment] 2016-01-04 12:40
I am going to release the fixed as 2.1.1

**Comment by akiradeveloper** [comment] 2016-01-04 13:34
@onlyjob  I have fixed this issue and pushed v2.1.1, which is compiled with 4.4-rc8 and run my regression tests in device-mapper-test-suite. I think you can use it but note that it's not tested even compiling with pre-4.3 kernel. I am almost sure it's OK because the fix is trivial but I recommend you to try compiling and test with pre-4.3 kernels if you are unsure.

**Comment by onlyjob** [comment] 2016-01-04 16:13
Thank you very much. All good with 4.2 and 4.3 kernels. :smile:

**Comment by akiradeveloper** [comment] 2016-01-04 23:34
So I will close this issue

**Closed by akiradeveloper** 2016-01-04 23:34 UTC
