### ISSUE TITLE
dm-writeboost  can't read superblock after formatting

### ISSUE THREAD

**Issue by disaster123** [akiradeveloper/dm-writeboost#61] opened 2015-07-07 10:30 UTC
I've created a dm writeboost device but i can't mount it after format and even a reboot always results in a NEW dm writeboost device instead of resume.

What's wrong here?

#dmsetup table
wb_disk4: 0 1953525168 writeboost  8:48 8:35 10 writeback_threshold 70 nr_cur_batched_writeback 32 sync_data_interval 600 update_sb_record_interval 0 read_cache_threshold 0

# mkfs.xfs -f -i size=2048 /dev/mapper/wb_disk4                                
meta-data=/dev/mapper/wb_disk4   isize=2048   agcount=32, agsize=7630958 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=0        finobt=0
data     =                       bsize=4096   blocks=244190646, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=0
log      =internal log           bsize=4096   blocks=119233, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0

# mount -a
mount: /dev/mapper/wb_disk4: can't read superblock

# dmesg
[ 1075.354170] XFS (dm-1): Mounting V4 Filesystem
[ 1075.401004] XFS (dm-1): Log inconsistent (didn't find previous header)
[ 1075.401013] XFS (dm-1): failed to find log head
[ 1075.401015] XFS (dm-1): log mount/recovery failed: error -5
[ 1075.401127] XFS (dm-1): log mount failed

**Comment by akiradeveloper** [comment] 2015-07-07 10:39
What kernel are you using? (`uname -r`)

**Comment by akiradeveloper** [comment] 2015-07-07 10:46
And, please do the same test after temporarily changing the following line in dm-writeboost-target.c from `1<<3` to `4`. This will tell us if your problem is as same as the one I'm fighting now.

```c
	r = dm_set_target_max_io_len(ti, 1 << 3);
```

**Comment by akiradeveloper** [comment] 2015-07-07 11:21
I am using 4.1.0-rc2 and tested your command but not reproduced.

**Comment by disaster123** [comment] 2015-07-07 12:00
Hi,

i'm using 3.18.17. May it be related to flush / sync?

Stefan

Am 07.07.2015 um 13:21 schrieb Akira Hayakawa:

**Comment by akiradeveloper** [comment] 2015-07-07 12:17
Hi Stefan,

Sorry for the bug. As I can't reproduce your problem in my server I need your help to solve this problem.

Your kernel is OK and I think dm-writeboost can work in your server.

I want to know that your device is created properly. Can you mount if you mkfs.ext4?

I found a very similar problem three days ago and I am dealing with it now https://github.com/akiradeveloper/dm-writeboost/issues/62. Changing the max_io_len from 8 to 4 can somehow eliminate the bug. Please try this (change the source code and recompile) and if your problem got solved, we can say we are seeing the same bug.

**Comment by disaster123** [comment] 2015-07-07 12:37
Sorry you mean 1<<3 to 1<<4 or to 4?

**Comment by akiradeveloper** [comment] 2015-07-07 12:39
I meant `1 << 3` to `1 << 2`. Sorry to confuse you

**Comment by disaster123** [comment] 2015-07-07 13:03
OK works fine than. But makes me frighten about using it in production.

**Comment by disaster123** [comment] 2015-07-07 13:05
But the problem that it recreates the whole writeboost device after each reboot stays. So after each reboot the devices are recreated
 dmsetup create wb_disk4 --table 0 1953525168 writeboost /dev/disk/by-id/wwn-0x5000c5007a26b917 /dev/disk/by-partlabel/writeboost4
takes 5-8 minutes and does not resume the device.

**Comment by akiradeveloper** [comment] 2015-07-07 13:26
> OK works fine than.

So I think we are sharing the same problem intrinsically.

> But makes me frighten about using it in production.

I will fix this problem as soon as possble. Your feedback definitely contributed to dm-writeboost's quality. Thanks.

> But the problem that it recreates the whole writeboost device after each reboot stays. So after each reboot the devices are recreated
dmsetup create wb_disk4 --table 0 1953525168 writeboost /dev/disk/by-id/wwn-0x5000c5007a26b917 /dev/disk/by-partlabel/writeboost4
takes 5-8 minutes and does not resume the device.

I think it does resume the logs if you didn't zeroed out the superblock of cache device after reboot. You can see if it is resuming the logs by checking dmesg. If it doesn't print out "Magic number invalid" it is resuming. Resuming typically takes as much as initialization so 5-8 minutes for your cache device is considerable.

Slow initialization is one of the shortcoming of dm-writeboost (see https://github.com/akiradeveloper/dm-writeboost/issues/59) coming from the log-structured nature.

**Comment by disaster123** [comment] 2015-07-07 14:08
OK i understand. My Cache device is pretty big. 1TB SATA HDD and 120GB SSD per HDD. So it seems this combination takes "ages".

**Comment by akiradeveloper** [comment] 2015-07-09 03:20
Hi Stefan,

Could you please try with v2.0.1?

**Comment by disaster123** [comment] 2015-07-09 07:24
Thanks, works.

Am 09.07.2015 um 05:20 schrieb Akira Hayakawa:

**Comment by akiradeveloper** [comment] 2015-07-09 07:29
Good. So I will close this issue.

**Closed by akiradeveloper** 2015-07-09 07:29 UTC
Labels: bug
