### ISSUE TITLE
Question regarding writeboost and MYSQL

### ISSUE THREAD

**Issue by joeey1984ad** [akiradeveloper/dm-writeboost#146] opened 2016-08-23 05:49 UTC
Hello, I was testing writeboost  with Percona 5.5 and sysbenck 0.4. The performance is great up until around 10GB DATA. The performance quicly diminishes to a very low TPS. I repeated same test with LVM-Cache and Bcache but TPS drops down 'steadily' Not 'quicly'. Is this due the block size ( and if so can it be changed? ) or is  this a normal behavior?

BTW. My Buffer Pool is quite high 56GB. My Cache SSD is 430GB.

I created a 400GB DATA with sysbench 0.4 like so,

sysbench --test=oltp --oltp-table-size=5990000000 --mysql-db=test1 --db-driver=mysql --mysql-user=root --mysql-password=  prepare

Test is a complex R/W. 
Results:

Test1. All 400GB DATA (5990000000 Rows) 

sysbench --test=oltp --db-driver=mysql --oltp-test-mode=complex --oltp-table-size=5990000000   --mysql-db=test1 --mysql-user=root --mysql-password= --max-time=60 --oltp-read-only=off --max-requests=0 --num-threa  ds=56 run
sysbench 0.4.12:  multi-threaded system evaluation benchmark

OLTP test statistics:
    queries performed:
        read:                            17080
        write:                           6100
        other:                           2440
        total:                           25620
    transactions:                        1220   (15.53 per sec.)
    deadlocks:                           0      (0.00 per sec.)
    read/write requests:                 23180  (808.07 per sec.)
    other operations:                    2440   (85.06 per sec.)

------------------------------------------------------------------------
Test2. around 80Gb DATA (350000000 Rows) with the same 400GB table 

 sysbench --test=oltp --db-driver=mysql --oltp-test-mode=complex --oltp-table-size=350000000  --mysql-db=test1 --mysql-user=root --mysql-password= --max-time=20 --oltp-read-only=off --max-requests=0 --num-threads=56 run
sysbench 0.4.12:  multi-threaded system evaluation benchmark

OLTP test statistics:
    queries performed:
        read:                            9198
        write:                           3285
        other:                           1314
        total:                           13797
    transactions:                        657    (30.93 per sec.)
    deadlocks:                           0      (0.00 per sec.)
    read/write requests:                 12483  (587.66 per sec.)
    other operations:                    1314   (61.86 per sec.)

-------------------------------------------------------------------------
Teest3. Around 1GB DATA (5000000 Rows) with the same 400GB table 

sysbench --test=oltp --db-driver=mysql --oltp-test-mode=complex --oltp-table-size=5000000  --mysql-db=test1 --mysql-user=root --mysql-password= --max-time=60 --oltp-read-only=off --max-requests=0 --num-threads=56 run

OLTP test statistics:
    queries performed:
        read:                            1128106
        write:                           402895
        other:                           161158
        total:                           1692159
    transactions:                        80579  (4027.58 per sec.)
    deadlocks:                             0      (0.00 per sec.)
    read/write requests:                 1531001 (76523.94 per sec.)
    other operations:                     161158 (8055.15 per sec.)

The results with LVM-Cache and Bcache With same hardware and Mysql configuration is pporximately 
Test1, 1700-2000 TPS
Test2, 2200-2800 TPS
Test3, 4400-4500 TPS

**Comment by akiradeveloper** [comment] 2016-08-23 06:55
@joeey1984ad Give me the configuration of writeboost.

**Comment by joeey1984ad** [comment] 2016-08-23 06:59
'dmsetup message mylv 2 writeback_threshold 70 nr_max_batched_writeback 32 read_cache_threshold 1'

BTW changing 'writeback_threshold 70' to 1 or 0 increases performance.

**Comment by joeey1984ad** [comment] 2016-08-23 07:02
Also I made a seperate table with 80GB Data ( around 350000000 rows) and the test was normal. It seems when a table grows higher than 100GB or so performance goes down.

**Comment by akiradeveloper** [comment] 2016-08-23 07:27
@joeey1984ad performance analysis is too difficult from remote site. I can give you advices but I can't see what's going on here.

**Comment by akiradeveloper** [comment] 2016-08-23 07:30
I don't know about the workload (how it submits ios to the block layer)

btw, read_cache_threshold isn't a boolean. please read the doc.

**Comment by joeey1984ad** [comment] 2016-08-23 07:31
I repeated the test several times just to make sure. Also I have been using Lvm-cache with mysql and have tested it with 1GB DATA, the performance degradation is gradual.

Do you think, this has something to do with log structure nature writeboost ?

**Comment by akiradeveloper** [comment] 2016-08-23 07:31
To analyze, you should determine which block request is slow in what situation.

**Comment by joeey1984ad** [comment] 2016-08-23 07:32
how?

**Comment by akiradeveloper** [comment] 2016-08-23 07:33
> Do you think, this has something to do with log structure nature writeboost ?

No. Rather, I think writeboost's log-structured nature can give same acceleration to the different datasets.

**Comment by akiradeveloper** [comment] 2016-08-23 07:34
You should see the sysstat first. And what is happening when the iops is going down

**Comment by joeey1984ad** [comment] 2016-08-23 07:37
Anyway, I felt like I had to post this issue since I did not notice this problem with other cache blocks devices.

**Comment by akiradeveloper** [comment] 2016-08-23 07:37
Maybe, I can reproduce the same problem in my environment because the dataset is 400GB and we have free softwares that emulate OLTP workloads (such as dbench)

**Comment by joeey1984ad** [comment] 2016-08-23 07:37
Sure .. that mayhelp clarify the issue.

**Comment by joeey1984ad** [comment] 2016-08-23 07:38
The speed is very good even higher than LVM cache up to around 80GB table size.

**Comment by akiradeveloper** [comment] 2016-08-23 07:50
@joeey1984ad Can you try this command before you start the workload?

```
dmsetup suspend mylv
dmsetup resume mylv
dmsetup message mylv 0 drop_caches
```

I guess writeback is happening and that's the reason of slowing down. I can't be sure because you didn't share all you actually did.

Also, see how writeback is going by the sysstat. how about writing to the caching device?

**Comment by akiradeveloper** [comment] 2016-08-23 07:59
it's a mantra to drop all dirty caches

**Comment by joeey1984ad** [comment] 2016-08-23 08:00
Ok, I will try
dmsetup suspend mylv
dmsetup resume mylv
dmsetup message mylv 0 drop_caches

Just to be sure no Data was dropped in neither of the block device caches I tried.
All I did was to 1.create the block device 2.Create DATA with sysbench 3.test 

What do you mean writing to the caching device? you mean writing to SSD alone?

**Comment by akiradeveloper** [comment] 2016-08-23 08:02
@joeey1984ad 

did you run dropping caches between 2 and 3?

**Comment by akiradeveloper** [comment] 2016-08-23 08:04
> Just to be sure no Data was dropped in neither of the block device caches I tried.

This is strange because you set writeback_threshold to 70

**Comment by joeey1984ad** [comment] 2016-08-23 08:05
no, in neither of LVM, BCACHE nor Writeboost. I will try your method and let you know.

**Comment by akiradeveloper** [comment] 2016-08-23 08:05
> What do you mean writing to the caching device? 

By seeing the sysstat you can see how much write per sec is done to the caching device

**Comment by akiradeveloper** [comment] 2016-08-23 08:06
> no, in neither of LVM, BCACHE nor Writeboost. I will try your method and let you know.

How confusing. Let's talk about writeboost alone

**Comment by joeey1984ad** [comment] 2016-08-23 08:07
@akiradeveloper I am just saying that the test I have done was the same through out all cache devices.

**Comment by joeey1984ad** [comment] 2016-08-23 08:08
Checking the sysstat might help but that alone would not tell you why such a dramatic slow down.

**Comment by joeey1984ad** [comment] 2016-08-23 08:37
Ok I have done what was suggested.

1.create the block device 2.Create DATA with sysbench 3.drop cache dmsetup suspend mylv, dmsetup resume mylv, dmsetup message mylv 0 drop_caches  4.test

Same result.

**Comment by akiradeveloper** [comment] 2016-08-23 08:41
How was the sysstat when it slowed down?

**Comment by akiradeveloper** [comment] 2016-08-23 08:44
You should find the clear boundary of drastically dropping the TPS and compare the two on the other sides of the boundary.

**Comment by akiradeveloper** [comment] 2016-08-23 08:46
> Checking the sysstat might help

Not just checking. Experienced engineer can infer what is happening in the system from the sysstat.

**Comment by akiradeveloper** [comment] 2016-08-23 08:53
Give me the dmsetup status after the test

**Comment by joeey1984ad** [comment] 2016-08-23 08:54
sorry i am not that experienced in sysstat area! maybe if we can test on your end?

**Comment by akiradeveloper** [comment] 2016-08-23 11:47
@joeey1984ad  so it's a good chance to analyze why writeboost slows down. btw, give me the `dmsetup status` which may tells me the reason.

**Comment by joeey1984ad** [comment] 2016-08-23 19:13
Ok, I have to setup the whole thing again and write the 400 GB DATA back. It may take a while.  I will provide both 'dmsetup status' and 'sysstat' during sysbench test.

**Comment by joeey1984ad** [comment] 2016-08-23 22:30
I have a question regarding block size 4k? Is there an option to raise the block size to a biger number. In LVM cache such an option exist. It is called chunk size. I know that if my chuck size is small in LVM the performance for mysql gets very bad. I was wondering if may be the same thing is happening here.

**Comment by akiradeveloper** [comment] 2016-08-23 22:35
> Is there an option to raise the block size to a biger number.

no. it's meaningless.

btw, are you running this test on VM?

**Comment by akiradeveloper** [comment] 2016-08-23 22:48
I will explain why cache block size is 4KB fixed in writeboost and why it's meaningless to change the value

1. the actual write io to the caching device is 512KB
2. according to the Amdahl's law, accessing the block on read-hit in 4KB or larger is trivial considering CPU and memory is much faster than storage and SSD is much faster than HDD.

In log-structured caching, the term cache block is different from other mediocre caching software that just reinvents set associative caching.

**Comment by joeey1984ad** [comment] 2016-08-23 22:52
No i have a dedicated Server 64GB Ram  E5-1630 v3

**Comment by akiradeveloper** [comment] 2016-08-23 23:05
56GB to the buffer pool out of total 64GB sounds too much for me.

and I don't get why you trying to optimize block ios while you are trying to optimize the workload at the MySQL level.

Did you run the test without any block caching driver?

**Comment by akiradeveloper** [comment] 2016-08-23 23:06
btw

```
Test1. All 400GB DATA (5990000000 Rows)

sysbench --test=oltp --db-driver=mysql --oltp-test-mode=complex --oltp-table-size=350000 00 --mysql-db=test1 --mysql-user=root --mysql-password= --max-time=60 --oltp-read-only=off --max-requests=0 --num-threa ds=56 run
```

why is the oltp-table-size so small?

**Comment by joeey1984ad** [comment] 2016-08-23 23:09
56GB is for testing purposes and there is plenty of  ram available.

You mean running mysql on a single HDD withut block cache?!

That will be crazy slow on a large database. I have tried i.

400 DATA on a single HDD. Perromance is exactly like writeboost - around 15-30 TPS

On LVM and Bcache, TPS is around 1700-2000

**Comment by joeey1984ad** [comment] 2016-08-23 23:10
That was a mistake, I put wrong DATA here. For the All 400GB DATA the test should be as follow

sysbench --test=oltp --db-driver=mysql --oltp-test-mode=complex --oltp-table-size=5990000000 --mysql-db=test1 --mysql-user=root --mysql-password= --max-time=60 --oltp-read-only=off --max-requests=0 --num-threa ds=56 run

**Comment by akiradeveloper** [comment] 2016-08-23 23:18
Why the results slow down as the dataset gets larger? explain

**Comment by joeey1984ad** [comment] 2016-08-23 23:23
Because the amount of data that mysql needs is much faster than HDD IOPS. That is why the larger the database the sloer the TPS. For example if I  create 5000000 rows ( 1GB) table on a single HDD. The performance is quite high. Around 40000 TPS. 
Same test running only 5000000 rows (1GB) on a 5990000000 Row (400GB DATA) table, the TPS drops to 20000
The whole point of using block cache is to increase the IO for large database.

**Comment by akiradeveloper** [comment] 2016-08-23 23:25
> the amount of data that mysql needs is much faster than HDD IOPS

Sorry, type mismatch... Don't compare two values that have different types

**Comment by joeey1984ad** [comment] 2016-08-23 23:27
@akiradeveloper I don't know what you mean!!!!

**Comment by akiradeveloper** [comment] 2016-08-23 23:27
> BTW changing 'writeback_threshold 70' to 1 or 0 increases performance.

How it increased?

**Comment by joeey1984ad** [comment] 2016-08-23 23:30
oh yes, if i change from 70 to 1. the performance gets much better.

on a 5000000 table. your writeboost with 'writeback_threshold 0' does a very high 4200 TPSon only 10MB buffer pool. Same test with 'writeback_threshold 70'  TPS is 3000

**Comment by akiradeveloper** [comment] 2016-08-23 23:32
Why do you set read_cache_threshold 1?

**Comment by joeey1984ad** [comment] 2016-08-23 23:33
changing  read_cache_threshold  did not do any performance issues for me. I just kept like writeback_threshold.

**Comment by akiradeveloper** [comment] 2016-08-23 23:34
did you try read_cache_threshold 0?

**Comment by akiradeveloper** [comment] 2016-08-23 23:35
```
read_cache_threshold (int) [Experimental]
  accepts: 0..127
  default: 0 (read caching disabled)
More than $read_cache_threshold * 4KB consecutive reads won't be staged.
```

**Comment by akiradeveloper** [comment] 2016-08-23 23:36
it's not a boolean

**Comment by akiradeveloper** [comment] 2016-08-23 23:37
> changing read_cache_threshold

changing the value from WHAT?

**Comment by joeey1984ad** [comment] 2016-08-23 23:37
from whatever the default is!

**Comment by akiradeveloper** [comment] 2016-08-23 23:38
huh? the default value is 0

**Comment by joeey1984ad** [comment] 2016-08-23 23:38
did I try read_cache_threshold 0? no. but I can try this time. I am writing another 400gb data as we are speaking.

**Comment by joeey1984ad** [comment] 2016-08-23 23:39
I changed from 0 to 1. does it make sense now?

**Comment by akiradeveloper** [comment] 2016-08-23 23:40
> did I try read_cache_threshold 0? no.

You should try.

> I changed from 0 to 1. does it make sense now?

setting the value to 1 is probably just harmful. Please set it to 0 to disable read-caching.

**Comment by joeey1984ad** [comment] 2016-08-23 23:41
again changing read_cache_threshold never made any improvements or dis improvements. I will try read_cache_threshold=0. In fact last time I tested I think read_cache_threshold  was 0.

**Comment by akiradeveloper** [comment] 2016-08-23 23:44
> on a 5000000 table. your writeboost with 'writeback_threshold 0' does a very high 4200 TPSon only 10MB buffer pool. Same test with 'writeback_threshold 70' TPS is 3000

It's reasonable because writeback to the backing store leads to slow read from the backing store.

**Comment by akiradeveloper** [comment] 2016-08-23 23:45
Let's fix read_cache_threshold to 0 and writeback_threshold is 0
don't forget the mantra before each test

**Comment by joeey1984ad** [comment] 2016-08-23 23:46
Another thing I should mention. when the DATA from sysbench is being written to block cache, the speed constant around 40-45 mb/s. There is however a slow down in writes ( 4-10mb/s ) in around 200GB but after a few minutes it goes back up.

**Comment by akiradeveloper** [comment] 2016-08-23 23:48
> There is however a slow down in writes ( 4-10mb/s ) in around 200GB but after a few minutes it goes back up.

Are you talking about writeboost?

it's just because of starting writeback? please see the sysstat!!!

**Comment by joeey1984ad** [comment] 2016-08-23 23:48
This happens only in writeboost.

**Comment by akiradeveloper** [comment] 2016-08-23 23:48
also take `dmsetup status` when it slows down

**Comment by joeey1984ad** [comment] 2016-08-23 23:50
OK

**Comment by akiradeveloper** [comment] 2016-08-23 23:50
Please test
read_cache_threshold 0 and writeback_threshold (0 and 70)
don't forget the mantra before each test (total 6 tests)

With the results, I will restart discussion.

**Comment by akiradeveloper** [comment] 2016-08-23 23:50
Please take `dmsetup status` **after** each test too

**Comment by joeey1984ad** [comment] 2016-08-23 23:51
Also, when the HDD is in RAID1 this behavior is much worse ( 1-2 mb/s ). I think the write speed never goes up anymore.

**Comment by akiradeveloper** [comment] 2016-08-23 23:55
> this behavior
which behavior

Please take `dmsetup status` **before and after** each test

**Comment by joeey1984ad** [comment] 2016-08-23 23:58
OK, it slowed down around 160GB.
here is 
dmsetup status
mylv: 0 3907029168 writeboost 27786965 111085757 874691 1093486 1093486 218795 36210348 0 329 0 0 3 2939 0 0 0 50191159 0 0 0 88677276 0 5699 19 10 writeback_threshold 0 nr_cur_batched_writeback 8 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 0

systat
![test](https://cloud.githubusercontent.com/assets/12181529/17913926/c7edd2f6-6952-11e6-8e38-f6825bb56e91.jpg)

**Comment by joeey1984ad** [comment] 2016-08-24 00:00
@akiradeveloper  "behavior" I mean slowing down of writes.

**Comment by akiradeveloper** [comment] 2016-08-24 00:02
@joeey1984ad 
Give me `lsblk`

and from the status it's clear that writeback is the culprit.

```
874691 1093486 1093486 218795
```

```python
>>> 218795 + 874691
1093486
```

**Comment by joeey1984ad** [comment] 2016-08-24 00:03
The slowing down is gone now!!!

**Comment by akiradeveloper** [comment] 2016-08-24 00:03
> The slowing down is gone now!!!

now... when?

**Comment by joeey1984ad** [comment] 2016-08-24 00:04
NAME       MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda          8:0    0 447.1G  0 disk
├─sda1       8:1    0  19.5G  0 part
│ └─md1      9:1    0  19.5G  0 raid1 /
├─sda2       8:2    0 427.1G  0 part
│ └─md2      9:2    0 427.1G  0 raid1
│   └─mylv 253:0    0   1.8T  0 dm    /home
└─sda3       8:3    0   511M  0 part  [SWAP]
sdb          8:16   0 447.1G  0 disk
├─sdb1       8:17   0  19.5G  0 part
│ └─md1      9:1    0  19.5G  0 raid1 /
├─sdb2       8:18   0 427.1G  0 part
│ └─md2      9:2    0 427.1G  0 raid1
│   └─mylv 253:0    0   1.8T  0 dm    /home
└─sdb3       8:19   0   511M  0 part  [SWAP]
sdc          8:32   0   1.8T  0 disk
└─mylv     253:0    0   1.8T  0 dm    /home
sdd          8:48   0   1.8T  0 disk

**Comment by joeey1984ad** [comment] 2016-08-24 00:05
about a minute ago. also when the peed goes higher, it never goes up to full 40-45 mb/s. It is around 20-30mb/s now.

**Comment by akiradeveloper** [comment] 2016-08-24 01:04
why do you increase `nr_max_batched_writeback` from the default 8?
I recommend you to set more smaller value in your workload. Please try the default value first

**Comment by joeey1984ad** [comment] 2016-08-24 01:30
Look. everything is in default mode. those values I only changed once.

**Comment by joeey1984ad** [comment] 2016-08-24 02:20
1. created "writeboost" in default mode

2. dropped cache   

3. Created 400GB ( 5990000000 Row ) DATA table with sysbench

 4. dmsetup status ( before sysbench test )
mylv: 0 3907029168 writeboost 100953446 111085757 874691 2544292 2544291 1669611 36764522 0 3730 0 0 3 4463 0 0 0 109163151 0 0 0 213957521 0 16272 19 10 writeback_threshold 0 nr_cur_batched_writeback 8 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 0

5. tested  with sysbench
------------------------------------------------------------------------------------------------
 sysbench --test=oltp --db-driver=mysql --oltp-test-mode=complex --oltp-table-size=5990000000  --mysql-db=test1 --mysql-user=root --mysql-password= --max-time=60 --oltp-read-only=off --max-requests=0 --num-threads=56 run
sysbench 0.4.12:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 56

Doing OLTP test.
Running mixed OLTP test
Using Special distribution (12 iterations,  1 pct of values are returned in 75 pct cases)
Using "BEGIN" for starting transactions
Using auto_inc on the id column
Threads started!
Time limit exceeded, exiting...
(last message repeated 55 times)
Done.

OLTP test statistics:
    queries performed:
        read:                            8330
        write:                           2975
        other:                           1190
        total:                           12495
    transactions:                        595    (9.63 per sec.)
    deadlocks:                           0      (0.00 per sec.)
    read/write requests:                 11305  (182.95 per sec.)
    other operations:                    1190   (19.26 per sec.)

Test execution summary:
    total time:                          61.7933s
    total number of events:              595
    total time taken by event execution: 3421.4349
    per-request statistics:
         min:                               1527.01ms
         avg:                               5750.31ms
         max:                              15799.43ms
         approx.  95 percentile:           10549.46ms

Threads fairness:
    events (avg/stddev):           10.6250/1.17
    execution time (avg/stddev):   61.0971/0.47

------------------------------------------------------------------------------------
5. dmsetup status  ( after sysbench test )
mylv: 0 3907029168 writeboost 100954976 111085757 874691 2544304 2544303 1669627 36763891 0 545462 0 0 3 4775 0 0 0 109163516 0 0 0 213958686 0 16369 19 10 writeback_threshold 0 nr_cur_batched_writeback 8 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 0

**Comment by akiradeveloper** [comment] 2016-08-24 02:24
@joeey1984ad 
You didn't drop the cache at 2

**Comment by joeey1984ad** [comment] 2016-08-24 02:27
yes. it took several hours and my computer hibernated so maybe putty got disconnected. Anyhow if you really think dropping is the issue I can restart serve and allow "reboot dropping cache" or you can do the test yourself!

**Comment by akiradeveloper** [comment] 2016-08-24 02:29
> yes.

huh? don't lie to me.

> I can restart serve and allow "reboot dropping cache"

meaningless.

**Comment by joeey1984ad** [comment] 2016-08-24 02:31
whatever, stick to what I provided or just do it yourself. Either way this is an issue that needs attention.

**Comment by akiradeveloper** [comment] 2016-08-24 02:31
I think there is nothing we can discuss any more.

It's just the writeback started and the write from MySQL is blocked. it's too simple.

**Comment by akiradeveloper** [comment] 2016-08-24 02:45
> Either way this is an issue that needs attention.

No. writeboost is just a caching driver so always depends on the workload. The consequence is reasonable. There is nothing new to discuss.

Maybe the scenario is:
The IO size from MySQL is large enough (look at the average request size to the sdc!!!) so other caching drivers skip them (write around).
On the other hand, writeboost always try to cache writes. Then, the caching becomes full and starts writeback.
Once writeback started, considering that the writes is restless, the upper layer always blocks and waits for writeback to make a new empty segment. Thus slows down the write.

In my opinion, your workload is fairly invalid to measure writeboost. What you observed when the dataset is small is the actual capability of writeboost.

Probably, you should try write_around_mode=1 and read_cache_threshold=127. If the setting isn't still effective, there is no way to make a good result in your workload.

**Comment by joeey1984ad** [comment] 2016-08-24 04:40
Arrogation fool, I just provided evidence that other  two caching device operate differently and you trying to come up with some lame excuse not to admit there is a FUNDAMENTAL flaw in writeboost. PLEASE

**Comment by akiradeveloper** [comment] 2016-08-24 05:10
@joeey1984ad

> Arrogation fool
> admit there is a FUNDAMENTAL flaw in writeboost.

Again. You lack respect to others. You are fooling others merely based on your selfish idea. Since there is no perfect caching solution, it's not fair to say "FUNDAMENTAL flaw".

I want to talk to only those who respect others and his/her software. It's ok you can continue to evaluate writeboost but I will not answer to any questions of yours until you change your attitude. 

I consider, the respectful attitude is what everyone involves OSS should have and you unfortunately lack this.

**Comment by akiradeveloper** [comment] 2016-08-24 05:12
I will close this issue because I won't answer any more.

**Closed by akiradeveloper** 2016-08-24 05:12 UTC
